
          

          <!-- Single button -->
        <div class="btn-group">
          <a 
          href=""
          type="button" 
          class="btn btn-default dropdown-toggle btn-success" 
          data-toggle="dropdown" 
          aria-haspopup="true" 
          aria-expanded="false">
            + Adicionar novo Telefone
          </a>
         
        </div>

          <h2 class="sub-header">Lista de Clientes</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Nome</th>
                  <th>Telefone</th>
                  <th>E-mail</th>
                  <th>Options</th>
                </tr>
              </thead>
              <tbody>
                
                 
               
                <tr>
                  <td>Hugo></td>
                  <td>31-975275084</td>
                  <td>hugovasconcelosf@hotmail.com</td>
                  <td>
                    <div class="btn-group" role="group">
                      <a type="button" class="btn btn-default btn-primary" href="">Editar</a>
                       <a type="button" class="btn btn-default btn-danger" href="">Deletar</a>
                     
                    </div>
                  </td>                  
                </tr>   
                           
              </tbody>
            </table>
          </div>
     